services:
  POSTGRES:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=alumno
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=coursesDb
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  MYSQL:
    image: mysql
    container_name: mysql-db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=alumno
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=studentsDb
    volumes:
      - ./volumes/mysql:/var/lib/mysql